### ISSUE TITLE
qaqc_keep not working?

### ISSUE THREAD

**Issue by magelcai** [fawda123/SWMPr#12]
I'm having issues with qaqc in SWMPr. I wish to keep all data with '0' and '4' (historical) flag, however qaqc_keep is not working to retain both types of data. Below is the code I'm using... I run the subset(qaqc...) code and all data with flags other than '0' have been converted to 'NA'. Please let me know if you have suggestions on how to do this properly.

> CharlestonNutrients_All <- import_local(path, 'soschnut')
> CharlestonNutrients_Final <- subset(qaqc(CharlestonNutrients_All), qaqc_keep = c('0', '4'), rem_cols = T)

**Comment by ebourque** [comment]
Morning Caitlin,

Try running
                CharlestonNutrients_Final <- subset(qaqc(CharlestonNutrients_All, qaqc_keep = c('0', '4')), rem_cols = T)

I believe that the issue you were running into was because you had a ‘)’ after CharlestonNutrients_All when it needed to be after c('0', '4').  That way it reads: qaqc Nut data and keep ‘0’, ‘4’, then subset the data and remove empty columns.

Hopefully this helps,

Ethan

**Comment by ebourque** [comment]
Morning again,

Kim wanted me to let you know that another option you might try it to remove the subset term.  She believes that in earlier versions of the package you had to use that, but not anymore. It’s just qaqc().

Ethan

**Comment by magelcai** [comment]
Hi Ethan, thanks so much for your quick reply. This was very helpful - moving the qaqc_keep term inside the qaqc parentheses fixed the problem! Thank You - Caitlin

**Comment by fawda123** [comment]
Hi, sorry I just saw this, not sure why I didn't get an email notification.  Looks like you got it figured out though.  

I think maybe we're confusing what `rem_cols` does in `subset`.  By default, `qaqc` removes the flag columns with the qaqc codes, i.e., those with `f_` in the column name.  `subset` with `rem_cols = TRUE` removes empty columns with NA values that aren't the qaqc code columns.  So you need to use both if you want to remove the qaqc columns and empty non-qaqc columns.  Make sense?
