### ISSUE TITLE
color blind palette options?

### ISSUE THREAD

**Issue by billpine** [fawda123/SWMPr#16]
# Issues reporting guide

Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Hi, This is a great package, but the green color shading can be hard to interpret for people with red-green colorblindness.  This shading is used in the monthly means and monthly anomalies plotting.   Including an option to call a color blind friendly palette may be useful for some users, and likely for their audiences as well.  Thank you for your efforts to develop and maintain this package.

```r
# insert reprex here
```

**Comment by fawda123** [comment]
@billpine how about this?  Here's an example with viridis palette colors.

```
plot_summary(dat, param = 'chla_n', year = c(2007, 2013), colsleft = c("#FDE725FF", "#21908CFF"), 
             colsmid = "#FDE725FF", colsright = c( "#FDE725FF", "#21908CFF", "#440154FF"))
```
![image](https://user-images.githubusercontent.com/3086881/106277423-0f8b1b80-6207-11eb-96b2-a4069a442b43.png)

**Comment by billpine** [comment]
Thanks, but not really for me.  I couldn’t identify these colors very easily.  I use something that looks more like this in heat maps, and also standardize to deviations from the mean.  So a value of 400 is 400% of the mean, which I think is more informative with some variables (like discharge) than the actual value. Other variables like dissolved oxygen, you may be more interested in the actual value.
