### ISSUE TITLE
all_params fxn to work with qaqc fxn

### ISSUE THREAD

**Issue by skdunnigan** [fawda123/SWMPr#18]
Hey Marcus, I just recently discovered your `all_params` functions in the package and when I used it, I realized that the data it pulls does not use angle brackets around the flag values in the f_ columns. So, when I proceeded to use the `qaqc` function, it simply replaces the entire dataset with NAs. Has this happened to you? Is there a workaround I missed? I know data downloaded through the CDMO comes in a variety of formats, but wondered if it was something I had done incorrectly through this workflow. 
Thanks!!

**Comment by fawda123** [comment]
Hi @skdunnigan, honestly I don't ever use the functions that call the CDMO API since it's so much faster just to download directly from the site.  Can you paste some code here that reproduces the issue?  I'm waiting on my IP address to be registered with CDMO.  Thanks!

**Comment by fawda123** [comment]
@skdunnigan I added a fix to `qaqc` to add the angle brackets.  It would be better to have CDMO add those for the data coming out of the direct web requests.  Maybe we should inquire with them to see if that's possible?  

Either way, just reinstall the package from GitHub and it should work. 
```
library(SWMPr)
dat <- all_params('hudscwq')
qaqc(dat)

#         datetimestamp temp spcond sal do_pct do_mgl depth  ph turb chlfluor level cdepth clevel
# 1  2021-12-06 09:15:00  3.4   0.38 0.2   96.4   12.8  0.40 8.0    7      2.3    NA     NA     NA
# 2  2021-12-06 09:30:00  3.4   0.38 0.2   96.4   12.8  0.40 8.0    7      2.3    NA     NA     NA
# 3  2021-12-06 09:45:00  3.4   0.38 0.2   96.6   12.8  0.40 8.0    7      2.3    NA     NA     NA
# 4  2021-12-06 10:00:00  3.5   0.38 0.2   96.8   12.9  0.40 8.0    7      2.4    NA     NA     NA
# 5  2021-12-06 10:15:00  3.5   0.38 0.2   96.8   12.9  0.40 8.0    7      2.4    NA     NA     NA
# 6  2021-12-06 10:30:00  3.5   0.38 0.2   97.1   12.9  0.39 8.0    7      2.3    NA     NA     NA
# 7  2021-12-06 10:45:00  3.5   0.38 0.2   97.5   12.9  0.38 8.0    7      2.4    NA     NA     NA
# 8  2021-12-06 11:00:00  3.6   0.38 0.2   97.8   13.0  0.38 8.0    7      2.5    NA     NA     NA
# 9  2021-12-06 11:15:00  3.6   0.38 0.2   98.3   13.0  0.37 8.0    7      2.6    NA     NA     NA
# 10 2021-12-06 11:30:00  3.6   0.38 0.2   98.9   13.1  0.38 8.1    7      2.6    NA     NA     NA
```

**Comment by skdunnigan** [comment]
@fawda123, thanks! I'm working on putting together a bunch of resources to work with SWMP data and have been documenting file differences as I reach each step. I know the CDMO is somewhat aware of the differences in their files with the downloads, but I'll try and be explicit in my notes if I can. It's crazy how accessing data from their database whether by API, the AQS (which is my preference as well!), or the Data Graphing Export System results in different file formats haha!
I'll download the package from GitHub this week and give your fix a go! Thank you!

**Comment by fawda123** [comment]
Yea, that's why I stuck with the zip downloads for the bulk data ingest with SWMPr.  I suppose it's up to CDMO if they want to change the output format of the data directly from the API.  The change I made to SWMPr is a band-aid solution, but good to bring to their attention anyway.  Thanks!
