### ISSUE TITLE
Please import only the functions you use from data.table

### ISSUE THREAD

**Issue by tdhock** [fawda123/SWMPr#19]
hi @fawda123 
There are several instances of `@import data.table` in your roxygen comments, which get converted to import(data.table) in your NAMESPACE, which has the effect of importing everything that data.table exports.
In the new version of data.table on github master, `remotes::install_github("Rdatatable/data.table")` there are new exported objects `yearmon` and `yearqtr`.
There are also exported objects with these same two names in package zoo which you also import.
This has the effect of generating the following new warning when I run R CMD check SWMPr with data.table github master installed:
```
* checking whether package 'SWMPr' can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import 'data.table::yearmon' by 'zoo::yearmon' when loading 'SWMPr'
  Warning: replacing previous import 'data.table::yearqtr' by 'zoo::yearqtr' when loading 'SWMPr'
```
The fix would be to use `@importFrom data.table as.IDate` etc (for only the objects you use), instead of `@import data.table`.
Please update your code, then run R CMD check SWMPr_vers.tar.gz with data.table master installed.
After you update your code and R CMD check has no more errors, please submit a new version of SWMPr to CRAN.
This will help facilitate releasing a new version of data.table to CRAN.
(data.table devs must make sure all reverse dependencies do not break, before submitting a new version to CRAN)

**Comment by fawda123** [comment]
Thanks @tdhock, I've fixed the imports as suggested and pushed a new version to CRAN. https://cran.r-project.org/web/packages/SWMPr/index.html

**Comment by tdhock** [comment]
great thanks!

**Comment by tdhock** [comment]
I confirm the warning has gone away.

**Comment by fawda123** [comment]
Awesome, thanks @tdhock.
