### ISSUE TITLE
Remove use oof maptools

### ISSUE THREAD

**Issue by rsbivand** [fawda123/SWMPr#20]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by fawda123** [comment]
Done with [v2.4.3](https://github.com/fawda123/SWMPr/releases/tag/v2.4.3) release

**Comment by rsbivand** [comment]
[00check.log](https://github.com/fawda123/SWMPr/files/11149413/00check.log)
Thanks for your cooperation!
