### ISSUE TITLE
Unable to Install Package due to Dependency Problem

### ISSUE THREAD

**Issue by guyrachelk** [fawda123/SWMPr#22]
I am trying install the latest version of SWMPr (my R Studio and R are up to date). I am using a Mac OS Monterey. Installation gets aborted because there appears to be a problem with openair. I am getting this error and have not been able to find a work around:

ERROR: compilation failed for package ‘openair’
* removing ‘/Users/Rachel/Documents/SWMP/
------------------------------------------------------------------------------ 
R was unable to find one or more FORTRAN libraries during compilation.
This often implies that the FORTRAN compiler has not been properly configured.
Please see https://stackoverflow.com/q/35999874 for more information.

Reason(s):
- 'ld: library not found for -lgfortran'
install of package 'openair' failed [error code 1]

**Comment by fawda123** [comment]
Hi, are you trying to install from GitHub or CRAN? The [CRAN mirrors](https://cran.r-project.org/web/checks/check_results_SWMPr.html) do not show any issues for Mac OS.

**Comment by guyrachelk** [comment]
I actually fixed the problem by installing FORTRAN off of the github website. Weird Mac problem.

Thanks for checking back with me.

From: Marcus W Beck ***@***.***>
Date: Tuesday, December 19, 2023 at 8:03 AM
To: fawda123/SWMPr ***@***.***>
Cc: Guy, Rachel ***@***.***>, Author ***@***.***>
Subject: Re: [fawda123/SWMPr] Unable to Install Package due to Dependency Problem (Issue #22)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi, are you trying to install from GitHub or CRAN? The CRAN mirrors<https://urldefense.com/v3/__https:/cran.r-project.org/web/checks/check_results_SWMPr.html__;!!HWVSVPY!lc4m3KKeJhsGzjYk4t93AKOA-feZEljjDyvDTNDmM_GcHrvaSrdIK_gszZkbRgUNdjJdqTrvzGH6AnROoJk4jUhaLn73$> do not show any issues for Mac OS.

**Comment by fawda123** [comment]
Ok, glad you got it figured out.  Cheers!
